src/components/Header/Header.tsx, src/containers/HeaderWrapper/HeaderWrapper.tsx, src/pages/FarmsPage/FarmsPage.tsx, src/pages/FarmsPage/style.ts
- hide devnet
- fix position of placeholder on farms page
=> UI improvements

package-lock.json, package.json
- fix install dependecies after delete package.-lock.json
=> override version of rpc websockes

package-lock.json, package.json, src/components/Header/Header.stories.tsx, src/components/Header/Header.tsx, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/Swap/Swap.tsx, src/containers/HeaderWrapper/HeaderWrapper.tsx, src/containers/WrappedStats/WrappedStats.tsx, src/static/icons.ts, src/static/svg/SolanaCreator/Cat1.svg, src/static/svg/SolanaCreator/Cat2.svg, src/static/svg/SolanaCreator/Dog1.svg, src/static/svg/SolanaCreator/Dog2.svg, src/store/consts/static.ts, src/store/reducers/solanaConnection.ts, src/store/reducers/stats.ts, src/store/sagas/stats.ts, src/store/sagas/wallet.ts, src/store/selectors/solanaWallet.ts, src/utils/utils.ts, src/utils/web3/programs/amm.ts
=> add mainnnet support

src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Snackbar/CustomSnackbar/CustomSnackbar.tsx, src/components/Swap/TokensInfo/SingleToken/SingleToken.tsx, src/utils/utils.ts
=> fix explorer url

src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Snackbar/CustomSnackbar/CustomSnackbar.tsx, src/components/Swap/TokensInfo/SingleToken/SingleToken.tsx, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/store/consts/static.ts, src/store/sagas/positions.ts, src/store/sagas/swap.ts, src/utils/utils.ts
- fixed timeout error on position details 
- update snackbar text 
- update common tokens 
- update explorer link
=> Timeout refresh on position details

src/components/AnimatedButton/style.ts, src/components/Inputs/DepositAmountInput/DepositAmountInput.stories.tsx, src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx, src/components/Inputs/DepositAmountInput/style.ts, src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Inputs/Select/Select.tsx, src/components/Inputs/Select/style.ts, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Modals/SelectModals/style.ts, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/Stats/PoolList/PoolList.tsx, src/components/Stats/PoolList/Stats.PoolList.stories.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokenListItem/style.ts, src/components/Stats/TokensList/Stats.TokenList.stories.tsx, src/components/Stats/TokensList/TokensList.tsx, src/components/Swap/Swap.tsx, src/components/Swap/TokensInfo/SingleToken/SingleToken.tsx, src/components/Swap/TokensInfo/styles.ts, src/components/Swap/style.ts, src/containers/WrappedStats/WrappedStats.tsx, src/utils/utils.ts
- background of animated button
- warning for unknown tokens
- trim zeros in inputs
=> align ui changes

src/utils/utils.ts
trim zeros at the beginning of number
=> update trimDecimalZeros function

.gitignore, package-lock.json, package.json, src/store/consts/static.ts, src/store/sagas/swap.ts, src/utils/utils.ts
- bump sdk version
- add simulation tick limits
=> add simulation tick limits

package-lock.json, package.json, src/store/sagas/positions.ts, src/store/sagas/swap.ts
- add wrapped eth util
- bump sdk version
=> add wrapped eth utils

src/components/Stats/Liquidity/Liquidity.tsx, src/components/Stats/Liquidity/style.ts, src/components/Stats/Volume/Volume.tsx, src/components/Stats/Volume/style.ts
=> refactor tooltip on volume and liquidity

package-lock.json, package.json, src/store/sagas/positions.ts
=> update locker sdk

src/store/sagas/positions.ts
- fix create position with eth
=> fix create position with eth

src/components/Header/Header.tsx, src/components/Header/HeaderButton/ChangeWalletButton.tsx, src/containers/HeaderWrapper/HeaderWrapper.tsx, src/containers/WrappedPoolList/WrappedPoolList.tsx, src/containers/WrappedStats/WrappedStats.tsx, src/pages/LeaderboardPage/config/index.ts, src/store/selectors/leaderboard.ts
search fix in both pools list
update points after wallet eager connect
add portfolio tab
=> Various points fixes

src/store/reducers/positions.ts, src/store/sagas/positions.ts
- add raw tick indexes to liquidity plot
- remove unused cache key
=> add raw tick indexes to plot ticks

src/components/Swap/Swap.tsx, src/store/sagas/pool.ts, src/utils/utils.ts
- fix checking for errors in swap
- add fallback error
- remove redundant cross tick checks
=> adjust error handling

package-lock.json, src/pages/BondsPage/styles.ts, src/pages/FarmsPage/style.ts, src/pages/LeaderboardPage/components/LeaderboardBanner/NormalBanner.tsx, src/pages/ListPage/styles.ts, src/pages/NewPositionPage/styles.ts, src/pages/PortfolioPage/styles.ts, src/pages/RootPage.tsx, src/pages/SingleFarmPage/style.ts, src/pages/SinglePositionPage/styles.ts, src/pages/SolanaCreator/styles.ts, src/pages/StatsPage/styles.ts, src/pages/SwapPage/styles.ts, src/store/consts/static.ts
- update banner. fix to not scroll 
- update promoted fee tier
=> update banner and promoted tiers

src/components/Snackbar/CustomSnackbar/CustomSnackbar.tsx
=> add close button to all snackbars

src/components/Pagination/Pagination.tsx
Reverts invariant-labs/webapp-eclipse#383
=> Revert "Pagination hotfix"

src/components/NewPosition/FeeSwitch/FeeSwitch.tsx
=> Fixed wrong if statement in Fee Tier selection

src/pages/LeaderboardPage/components/LeaderboardItem/LeaderboardItem.tsx, src/pages/LeaderboardPage/components/LeaderboardItem/style.ts, src/pages/LeaderboardPage/components/LeaderboardList/LeaderboardList.tsx, src/pages/LeaderboardPage/components/TopScorers/ScorerItem.tsx, src/pages/LeaderboardPage/components/TopScorers/TopScorers.tsx, src/pages/LeaderboardPage/components/TopScorers/styles.ts, src/store/reducers/leaderboard.ts
=> add domains as addresses

src/components/Swap/Swap.tsx
=> update price impact warning

src/components/Modals/PromotedPoolPopover/PromotedPoolPopover.tsx, src/components/Modals/PromotedPoolPopover/style.ts, src/components/PopularPools/Card/Card.tsx, src/components/PopularPools/PopularPools.tsx, src/pages/LeaderboardPage/components/PoolListItem/PoolListItem.tsx
=> fix apy apr on popular pools

src/components/Modals/Slippage/Slippage.tsx, src/components/Modals/Slippage/style.ts
Change the background in case of Custom Slippage tolerance (Similar to the predefined value 0.3%, 0.5% 1%)
=> custom slippage active background 

src/components/Swap/style.ts
=> fix swap top margin

src/components/Leaderboard/Switcher/LeaderboardSwitcher/style.ts
=> align arrow of dropdown

src/components/Leaderboard/RewardedPools/PoolList/PoolList.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/PoolListItem.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/Variants/CustomPoolListItem.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/Variants/style.ts, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/style.ts, src/components/Leaderboard/RewardedPools/PoolList/style.ts, src/components/LiquidityPoolList/style.ts, src/components/Stats/PoolList/style.ts, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokenListItem/style.ts, src/components/Stats/TokensList/style.ts, src/static/theme/index.ts
=> refactor tables ui

src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx, src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/PositionDetails/SinglePositionInfo/BoxInfo.tsx, src/utils/utils.ts
new format number, applied to estimated price for swap input
=> new format number

src/components/PopularPools/PopularPools.tsx, src/components/PopularPools/style.ts
=> add arrows to popular pools slider

src/components/NewPosition/NewPosition.tsx
=> move concentrationTypeSwitch to right on mobile

src/components/Header/HeaderButton/ChangeWalletButton.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolList.tsx, src/components/Leaderboard/YourProgress/ProgressItem.tsx, src/components/Modals/PromotedPoolPopover/PromotedPoolPopover.tsx, src/components/PopularPools/Card/Card.tsx, src/components/PositionsList/PositionItem/variants/PositionItemDesktop.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/store/reducers/leaderboard.ts
- make value of position be displayed in denominator token
- set points to zero on wallet disconnect
- make airdrop tooltips open on click instead of hover
- fix apr and apy calculations in rewarded pools section
- center values in your progress section
- fix total points tooltip on mobile
=> Bug fixes 5

src/components/LiquidityPoolList/style.ts, src/components/Pagination/Pagination.tsx, src/components/Pagination/style.tsx, src/components/Stats/PoolList/style.ts, src/components/Stats/TokensList/style.ts
=> pagination fix

index.html, src/pages/RootPage.tsx
=> Dynamic title

src/components/Modals/Slippage/Slippage.tsx, src/components/TokenCreator/NumericInput/NumericInput.tsx
Decimal input mode set where needed
=> Input types changes

src/components/Leaderboard/LeaderboardList/LeaderboardList.tsx, src/components/Leaderboard/LeaderboardList/style.ts, src/components/Pagination/Pagination.tsx, src/components/Pagination/style.tsx, src/components/Stats/TokensList/style.ts
Fix paddings on pager mobile view in points table
=> Points pager paddings mobile fix

src/components/FooterNavbar/style.ts
Nightly Connector overlapping mobile navbar fixed
=> Nightly Connector overlap fix

src/components/Modals/SocialModal/SocialModal.tsx, src/components/Modals/SocialModal/style.ts
- opens in new tab
- hover added
- opens clicking on whole row
=> Social modal fix

src/components/AnimatedNumber/AnimatedNumber.stories.tsx, src/components/AnimatedNumber/AnimatedNumber.tsx, src/components/FilterSearch/Helpers/TokenOption.tsx, src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx, src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Modals/LockLiquidityModal/LockLiquidityModal.tsx, src/components/Modals/LockStatsPopover/LockStatsPopover.tsx, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/NewPosition/EstimatedPoints/EstimatedPoints.tsx, src/components/NewPosition/EstimatedPoints/PointsLabel.tsx, src/components/NewPosition/PoolInit/PoolInit.tsx, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/PopularPools/Card/Card.tsx, src/components/PositionDetails/LiquidationRangeInfo/LiquidationRangeInfo.tsx, src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/SinglePositionInfo/BoxInfo.tsx, src/components/PositionsList/PositionItem/variants/PositionItemDesktop.tsx, src/components/PositionsList/PositionItem/variants/PositionItemMobile.tsx, src/components/PriceRangePlot/PriceRangePlot.tsx, src/components/Stats/Liquidity/Liquidity.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/Volume/Volume.tsx, src/components/Stats/volumeBar/VolumeBar.tsx, src/components/Swap/EstimatedPointsLabel/EstimatedPointsLabel.tsx, src/components/Swap/ExchangeRate/ExchangeRate.tsx, src/components/Swap/TokensInfo/SingleToken/SingleToken.tsx, src/components/Swap/TransactionDetailsBox/TransactionDetailsBox.tsx, src/utils/utils.ts
=> current price format , and functions rename

src/components/Leaderboard/Claim/RewardsList/RewardsList.tsx, src/store/consts/rewards/rewardsArray.json
=> Rewards section update

src/components/FilterSearch/Helpers/TokenOption.tsx
=> decrease link button area

src/pages/LeaderboardPage/styles.ts, src/pages/ListPage/styles.ts, src/pages/NewPositionPage/styles.ts, src/pages/PortfolioPage/styles.ts, src/pages/SinglePositionPage/styles.ts, src/pages/StatsPage/styles.ts, src/pages/SwapPage/styles.ts, src/pages/TokenCreatorPage/styles.ts, src/pages/style.ts
Deleted unused space on all pages
=> Top margins mobile removal

src/components/Leaderboard/Switcher/LeaderboardSwitcher/style.ts, src/components/Leaderboard/YourProgress/BlurOverlay.tsx, src/components/RpcErrorModal/RpcErrorModal.tsx, src/components/RpcErrorModal/style.ts
fixed overlaying blurs from 
- your progress
- wallet selector
- rpc error modal
=> Fix overlaying blurs

src/components/FooterNavbar/style.ts, src/components/Leaderboard/LeaderboardList/LeaderboardItem/LeaderboardLpItem.tsx, src/components/Leaderboard/LeaderboardList/LeaderboardItem/LeaderboardSwapItem.tsx, src/components/Leaderboard/LeaderboardList/LeaderboardItem/LeaderboardTotalItem.tsx, src/components/Modals/Faucet/Faucet.tsx, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx, src/components/Snackbar/CustomSnackbar/CustomSnackbar.tsx, src/components/Snackbar/CustomSnackbar/style.ts, src/components/Snackbar/index.tsx, src/containers/HeaderWrapper/HeaderWrapper.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/containers/WrappedSwap/WrappedSwap.tsx, src/store/consts/static.ts, src/store/sagas/connection.ts, src/store/sagas/creator.ts, src/store/sagas/locker.ts, src/store/sagas/positions.ts, src/store/sagas/swap.ts, src/store/sagas/wallet.ts
- Removed dots from snackbars
- Add new tab icon
=> Snackbars dots fix

src/components/Stats/Liquidity/Liquidity.tsx, src/components/Stats/Liquidity/style.ts, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokenListItem/style.ts, src/components/Stats/Volume/Volume.tsx, src/components/Stats/Volume/style.ts, src/components/Stats/volumeBar/style.ts
Margins and paddings changed in stats pages
=> margin mobile change

src/components/PriceRangePlot/PriceRangePlot.tsx
fixed a bug where selecting the same token twice, switching to Range mode, changing the second input to a different token, and then selecting the original token again caused an issue.
=> New position undefined fix 

src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Modals/SelectModals/SelectTokenModal/style.ts
- MCT Token overlapping unkown token icon fix
- Changed the way to handle blinking unknown icons
=> Select tokens modal icons fix

package-lock.json, package.json, src/pages/RootPage.tsx, src/store/reducers/solanaWallet.ts, src/store/sagas/wallet.ts
Changing account in wallet in browser extension refreshes requierd data in webapp.
=> change wallet in extension

src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/style.ts
adjusted button hovers Reset range etc
=> New position buttons hover fix

src/components/FilterSearch/FilterSearch.tsx
added usd sorting  in search list
=> USD Balance Sorting in Search 

src/components/FooterNavbar/style.ts, src/components/NewPosition/NewPosition.tsx, src/components/PositionsList/style.ts
fix shrink window view up to 330px , 
bug cases:
=> fix width of view window

src/components/EmptyPlaceholder/EmptyPlaceholder.tsx, src/components/NoConnected/NoConnected.tsx, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx
fixed case:
refresh position details on not existing position and connected wallet -> for sec was shown 'not connected' placeholder
=> prevent replacing placeholder on position details

src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/style.ts
Slider fix, the rest part of the bug is reported to MUI:
https://github.com/mui/material-ui/issues/45434
=> Slider fix

src/components/FilterSearch/FilterSearch.tsx, src/components/FilterSearch/Helpers/ListBoxComponent.tsx, src/components/FilterSearch/Helpers/style.ts, src/components/FilterSearch/styles.ts
=> update search token modal

src/components/Modals/LeaderboardTypeModal/style.ts
=> leadboard dropdown fix

src/components/NewPosition/FeeSwitch/style.ts
=> Arrow Color change

src/components/PositionDetails/SinglePositionInfo/BoxInfo.tsx
=> Position Details zeros trim

src/components/NewPosition/NewPosition.tsx
fix bug with error occuring if entered concentration in url is less than 2
=> fix too small concentration bug

src/components/NewPosition/ConcentrationSlider/ConcentrationSlider.tsx, src/components/NewPosition/ConcentrationSlider/style.ts, src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/style.ts
=> slider align

src/static/icons.ts
=> Icons autocompletion

src/components/Snackbar/index.tsx
on larger screen snackbar covered mobile navbar
=> snackbar fix

src/components/PopularPools/Card/Card.tsx, src/components/Swap/Swap.tsx
adjust the denominator for tokens in exchange, when navigating from popular card
=> change denomiator for exchange rate ratio

src/components/PositionsList/PositionItem/components/MinMaxChart/MinMaxChart.tsx, src/components/PositionsList/PositionItem/variants/PositionMobileCard/PositionItemMobile.tsx, src/components/PositionsList/PositionItem/variants/PositionTables/PositionsTableRow.tsx
=> Full range price display

src/components/Modals/SelectWalletModal/SelectWalletModal.tsx, src/containers/HeaderWrapper/HeaderWrapper.tsx, src/utils/web3/wallet.ts
Production Issue: incognito > connect wallet > whatever static wallet > F5 on app
=> prevent opening new tab on refresh

src/components/Leaderboard/Leaderboard.tsx, src/components/Leaderboard/YourProgress/YourProgress.tsx, src/components/Modals/ContentPoints/ContentPointsModal.tsx, src/containers/LeaderboardWrapper/LeaderboardWrapper.tsx, src/store/reducers/leaderboard.ts, src/store/sagas/leaderboard.ts, src/store/selectors/leaderboard.ts
fetch dates of current content program season from API instead of hardcoded values
=> Fetch content program dates from API

src/components/Leaderboard/LeaderboardList/EmptyRow/styles.tsx, src/components/Leaderboard/LeaderboardList/LeaderboardItem/style.ts, src/components/Leaderboard/LeaderboardList/LeaderboardList.tsx
Fix interface jumping when changing a page
=> Points table height fix

src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Swap/ExchangeRate/ExchangeRate.tsx, src/components/Swap/TransactionDetailsBox/TransactionDetailsBox.tsx
Formatting Estimated value on swap page 
to exact value (as in add position)
=> added formmatting without suffix on swap page

src/common/EmptyPlaceholder/EmptyPlaceholder.tsx, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/pages/PortfolioPage/PortfolioPage.tsx, src/pages/PortfolioPage/styles.ts
fix placeholder for position details when wallet is disconnected
=> placeholder fix

src/components/PositionsList/PositionsList.tsx, src/components/PositionsList/style.ts
before ![image](https://github.com/user-attachments/assets/a7141bb6-487e-44d6-961b-d90b053d8ec1)
after
=> Position list design align

src/components/Leaderboard/EcosystemExposure/EcosystemExposure.tsx
=> exposure skeleton align

src/containers/EventsHandlers/market.ts
=> Add subcription on autoswap pool

src/components/Leaderboard/EcosystemExposure/EcosystemExposure.tsx, src/components/Leaderboard/YourProgress/ProgressItem.tsx, src/components/Leaderboard/YourProgress/YourProgress.tsx
Skeleton only appears when wallet is connected in Your Progress section
=> Your progress skeleton

src/common/PriceRangePlot/PriceRangePlot.tsx, src/common/PriceRangePlot/style.ts
=> fix chart handles

src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx, src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Inputs/RangeInput/RangeInput.tsx, src/components/Inputs/SimpleInput/SimpleInput.tsx, src/components/Modals/Slippage/Slippage.tsx
Converts comas to dots in numeric inputs
=> Change regex to allow comas

src/components/Leaderboard/LeaderboardList/LeaderboardList.tsx, src/components/Leaderboard/LeaderboardList/style.ts
=> add border for footer on leaderboard

src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokenListItem/style.ts
=> ticker token list fix

src/components/PositionDetails/PositionHeader/style.ts
=> icons align

src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/store/reducers/positions.ts, src/store/sagas/positions.ts, src/store/selectors/positions.ts
Fix skeleton when you cancel transaction
=> fix claim fee skeleton

src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/PositionHeader/PositionHeader.tsx, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/store/consts/static.ts
Add position button on position details should open proper tokens in new position.
=> fix add position button

src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/SinglePositionInfo/Liquidity/Liquidity.tsx, src/components/PositionDetails/SinglePositionInfo/SinglePositionInfo.tsx, src/components/PositionDetails/SinglePositionInfo/TokenDetails/TokenDetails.tsx, src/components/PositionDetails/SinglePositionInfo/UnclaimedFees/UnclaimedFees.tsx, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx
=> loader fix

src/components/Portfolio/PositionItem/PositionTables/skeletons/PositionCardsSkeletonMobile.tsx, src/components/Portfolio/PositionItem/PositionTables/skeletons/mobileSkeleton.ts
=> align mobile position item placeholder

src/store/sagas/leaderboard.ts
Fetch price feeds & content program from api.invariant.app
=> Use migrated leaderboard routes

src/store/consts/static.ts
=> update BITZ image

.github/workflows/deploy-prod.yml, .github/workflows/deploy-staging.yml, .github/workflows/preview.yml
=> bump action versions

src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/style.ts
=> add refresher to initPool

src/components/Leaderboard/RewardedPools/PoolList/PoolList.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/Variants/MobilePoolListItem.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/Variants/style.ts
=> update rewarded pool item on mobile

src/components/Leaderboard/YourProgress/YourProgress.tsx
=> tooltip title changed

src/components/Leaderboard/LeaderboardBanner/NormalBanner.tsx
redirect to pool bitz - eth - 1_00
=> banner redirect change

src/components/LiquidityPoolList/LiquidityPoolList.tsx, src/components/LiquidityPoolList/style.ts, src/components/Stats/PoolList/PoolList.tsx, src/components/Stats/PoolList/style.ts, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/PoolListItem/Stats.PoolListItem.stories.tsx, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokenListItem/style.ts, src/components/Stats/TokensList/TokensList.tsx, src/components/Stats/TokensList/style.ts, src/store/consts/static.ts
=> footer fix

src/components/PopularPools/Card/Card.tsx, src/components/PopularPools/Card/style.ts
avoid changing ticker position when points indicator loads
=> card ticker fix

src/components/Modals/FAQModal/FAQModal.tsx, src/components/Modals/FAQModal/styles.ts
=> faq modal links fix

src/common/Snackbar/CustomSnackbar/variants/TokensDetailsSnackbar.tsx
=> Arrow snackbar fix

src/components/Swap/Swap.tsx
=> #147 fix button message

src/components/PositionDetails/PositionHeader/PositionHeader.tsx, src/components/PositionDetails/SinglePositionInfo/SinglePositionInfo.tsx
=> [190] fix empty tooltips

src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx
couldn't reproduce the bug, but the solution should fix it.
=> [213] prevent wrong range view of chart

src/components/PopularPools/Card/style.ts
=> [210] change margin popular cards

src/common/TooltipHover/TooltipHover.tsx, src/components/Portfolio/PositionItem/PositionMobileCard/PositionItemMobile.tsx
=> [202] fix fee tier width

src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx
=> [216] change format of min - max on position details

src/components/NewPosition/NewPosition.tsx, src/utils/utils.ts
=> [198] one tick spacing for max conc

src/common/TooltipHover/TooltipHover.tsx
=> [234] empty tooltip title fix

src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx
=> [249] current price loader

src/components/Portfolio/Overview/Overview/Overview.tsx, src/components/Portfolio/Overview/OverviewPieChart/ResponsivePieChart.tsx
=> [251] fix pie chart

src/store/hooks/userOverview/useAverageLogoColor.ts
=> [259] add brighter tickers

src/components/NewPosition/RangeSelector/style.ts
=> [275] fix margin on range view mobile

src/common/PriceRangePlot/PriceRangePlot.tsx, src/components/PositionDetails/PositionHeader/PositionHeader.tsx, src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx, src/static/icons.ts, src/static/svg/centerToRange.svg
=> [284] center chart by range

src/components/PositionDetails/Navigation/DesktopNavigation/DesktopNavigation.tsx, src/components/PositionDetails/Navigation/MobileNavigation/MobileNavigation.tsx, src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/PositionHeader/style.ts, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx
navigate to the closest position, after close current postion
=> [282] handle navigation after close position

src/common/Snackbar/CustomSnackbar/variants/TokensDetailsSnackbar.tsx, src/common/Snackbar/index.tsx, src/store/sagas/positions.ts, src/store/sagas/swap.ts
=> [237 use ticker istead of icons for unknown tokens

src/components/Bar/SettingsModal/SelectNetworkAndRPC/SelectNetworkAndRPC.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/store/consts/static.ts, src/store/reducers/pools.ts, src/store/reducers/solanaConnection.ts, src/utils/utils.ts
Reverts invariant-labs/webapp-eclipse#916
=> Revert "Update prod (BITZ-ETH fix loading fix)"

src/components/Bar/SettingsModal/SelectNetworkAndRPC/SelectNetworkAndRPC.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/store/consts/static.ts, src/store/reducers/pools.ts, src/store/reducers/solanaConnection.ts, src/utils/utils.ts
Reverts invariant-labs/webapp-eclipse#917
=> Revert "Revert "Update prod (BITZ-ETH fix loading fix)""

src/common/Separator/Separator.tsx, src/common/Separator/styles.ts, src/components/NewPosition/NewPosition.tsx, src/components/Stats/Intervals/Intervals.tsx, src/components/Stats/Intervals/style.ts, src/components/Stats/Liquidity/Liquidity.tsx, src/components/Stats/Liquidity/style.ts, src/components/Stats/Volume/Volume.tsx, src/components/Stats/Volume/style.ts, src/containers/WrappedStats/WrappedStats.tsx, src/containers/WrappedStats/styles.ts, src/store/reducers/pools.ts, src/store/reducers/solanaConnection.ts
=> add separator on stats

src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/DepositSelector/style.ts
=> update price impact loader

src/components/Stats/Liquidity/Liquidity.tsx, src/components/Stats/Volume/Volume.tsx
=> change chart area opacity

src/common/Pagination/InputPagination/InputPagination.tsx, src/common/TooltipHover/TooltipHover.tsx, src/common/TooltipHover/style.ts, src/components/Portfolio/Portfolio.tsx, src/components/Portfolio/PositionItem/PositionMobileCard/PositionItemMobile.tsx, src/components/Portfolio/PositionItem/PositionTables/PositionTableRow/PositionsTableRow.tsx, src/components/Portfolio/PositionItem/components/InactivePoolsPopover/InactivePoolsPopover.tsx, src/components/Portfolio/PositionItem/components/PositionStatusTooltip/PositionStatusTooltip.tsx, src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/PositionHeader/PositionHeader.tsx, src/components/PositionDetails/SinglePositionInfo/PositionStats/PositionStats.tsx, src/components/PositionDetails/SinglePositionInfo/SinglePositionInfo.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx
=> 304 update airdrop indicator

src/components/NewPosition/RangeSelector/style.ts
=> [317] update price warning on mobile

src/components/Modals/LockStatsPopover/LockStatsPopover.tsx
=> [324] format amounts on lock modal

src/components/Stats/Intervals/style.ts, src/components/Stats/Liquidity/Liquidity.tsx, src/components/Stats/Volume/Volume.tsx
=> change volume, liquidity formatting

src/components/Inputs/RangeInput/RangeInput.tsx, src/components/Modals/SelectWalletModal/SelectWalletModal.tsx, src/components/NewPosition/EstimatedPoints/EstimatedPoints.tsx, src/components/NewPosition/EstimatedPoints/PointsLabel.tsx, src/components/NewPosition/FeeSwitch/FeeSwitch.tsx, src/components/PositionDetails/SinglePositionInfo/PoolDetails/PoolDetails.tsx, src/components/PositionDetails/SinglePositionInfo/PositionStats/PositionStats.tsx, src/components/PositionDetails/SinglePositionInfo/TokenDetails/TokenDetails.tsx, src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx, src/store/consts/static.ts, src/utils/uiUtils.ts, src/utils/utils.ts
=> fix calc min max percentage

src/common/Pagination/InputPagination/style.tsx
=> update pagination input

src/components/Inputs/SimpleInput/SimpleInput.tsx, src/components/Inputs/SimpleInput/style.ts, src/components/NewPosition/PoolInit/PoolInit.tsx
=> update suggested price

src/components/PositionDetails/SinglePositionPlot/Stat/style.ts
=> align labels width

src/containers/NewPositionWrapper/NewPositionWrapper.tsx
=> hide promoted fee tier for one selected token

src/components/Swap/style.ts
=> increase swap width

src/common/TooltipHover/TooltipHover.tsx, src/components/Modals/DepositOptionsModal/DepositOption.tsx, src/components/Modals/DepositOptionsModal/style.ts, src/components/Modals/SwapPointsPopover/SwapPointsPopover.tsx, src/components/NewPosition/DepositSelector/DepositSelector.tsx
=> [384, 386] tooltips improvements

src/common/NoConnected/NoConnected.tsx, src/components/Header/Header.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/PoolListItem.tsx, src/components/Leaderboard/RewardedPools/PoolList/PoolListItem/Variants/MobilePoolListItem.tsx, src/components/LiquidityPoolList/LiquidityPoolList.tsx, src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/style.ts, src/components/PopularPools/Card/Card.tsx, src/components/Portfolio/Overview/YourWallet/ActionButtons/ActionButtons.tsx, src/components/Portfolio/Portfolio.tsx, src/components/Portfolio/PositionItem/PositionTables/PositionTable.tsx/PositionsTable.tsx, src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/PositionHeader/PositionHeader.tsx, src/components/Stats/PoolList/PoolList.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/containers/HeaderWrapper/HeaderWrapper.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/containers/PortfolioWrapper/PortfolioWrapper.tsx, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/static/icons.ts, src/store/reducers/index.ts, src/store/reducers/navigation.ts, src/store/selectors/navigation.ts
It depends on the route you are entering from
=> [255] Back arrows

package-lock.json, src/components/Swap/Swap.tsx, src/components/Swap/TokensInfo/styles.ts, src/components/Swap/style.ts
=> [429] swap mobile change

src/components/Modals/SelectWalletModal/SelectWalletModal.tsx, src/components/Modals/SelectWalletModal/styles.ts
=> [433] Wallet small screen change

src/components/Stake/YourStakeStats/YourProgress.tsx, src/containers/StakeWrapper/WrappedStake.tsx
- Connect yield24
- Use tooltips where it is necessary and fill them with correct description
- Set value decimal to 2 places
=> Your stats component

src/common/Faq/Faq.tsx, src/components/Stake/FAQSection/FAQSection.tsx
- Changed faq text
- Add bold to text
=> SBitz FAQ update

package-lock.json, src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/RangeSelector/PriceWarning/PriceWarning.tsx, src/components/NewPosition/RangeSelector/PriceWarning/style.ts, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/NewPosition/RangeSelector/style.ts, src/components/Swap/Swap.tsx, src/components/Swap/style.ts, src/containers/NewPositionWrapper/NewPositionWrapper.tsx
=> 395 update price warning

src/components/Swap/Swap.tsx, src/components/Swap/style.ts
=> Price error align

src/components/Leaderboard/EcosystemExposure/ExposureTooltipTitle/ExposureTooltipTitle.tsx
=> [491] ecosystem exposure link align

src/components/Stake/LiquidityStaking/Switcher/style.ts
=> [492] stake switcher tab width

src/common/TooltipHover/TooltipHover.tsx, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/FeeSwitch/FeeSwitch.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/static/icons.ts, src/static/svg/plusDisabled.svg, src/store/consts/static.ts
- Added possibility to disable some pools from UI
=> [472] Disabling Fee tiers 

src/components/NewPosition/ConcentrationSlider/ConcentrationSlider.tsx, src/components/NewPosition/ConcentrationSlider/style.ts, src/static/theme/index.ts
=> Slider adjustment

src/components/Stats/TokensList/TokensList.tsx, src/components/Stats/TokensList/style.ts
- Added footer in token list table (Empty placeholder) and fixed jumping layout after clicking `Show favourites` when list is empty
=> [494] Added footer separator

src/components/Stake/YourStakeStats/YourProgress.tsx, src/components/Stake/YourStakeStats/styles.ts, src/containers/StakeWrapper/WrappedStake.tsx, src/containers/StakeWrapper/styles.ts
- Prevent layout shifts while refreshing
=> [502] Fix skeletons and stake panel widths

src/components/PreSale/BuyComponent/BuyComponent.tsx, src/components/PreSale/BuyComponent/style.ts
=> add terms and conditions

src/components/PreSale/BuyComponent/BuyComponent.tsx, src/containers/PreSaleWrapper/PreSaleWrapper.tsx, src/utils/uiUtils.ts
-fix percentage scale
- fix max button
- change $INVT to INVT
=> fix 4 round bugs

package-lock.json, src/components/PreSale/BuyComponent/style.ts, src/components/PreSale/RoundComponent/RoundComponent.tsx
=> Layout change

package-lock.json, package.json, src/components/PreSale/RoundComponent/RoundComponent.tsx, src/containers/PreSaleWrapper/PreSaleWrapper.tsx, src/store/consts/static.ts, src/store/reducers/sale.ts, src/store/sagas/sale.ts, src/store/selectors/sale.ts, src/utils/utils.ts
- Verify user eligibility using API
- Cache the proof with 1h TTL per wallet
=> Connect eligibility checker

src/common/Button/Button.tsx, src/common/Button/styles.ts, src/components/Modals/ConfirmModal/style.ts, src/components/Modals/ConfirmModal/useConfirm.tsx, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/static/theme/index.ts
- Added confirm modal when you add position with price warning
Design and text can be changed later
=> [471] Confirm price warning modal

src/components/PreSale/Overlay/Overlay.tsx, src/components/PreSale/RoundComponent/RoundComponent.tsx, src/components/PreSale/RoundComponent/style.ts, src/components/PreSale/SaleStepper/SaleStepper.tsx, src/components/PreSale/SaleStepper/style.ts, src/containers/PreSaleWrapper/PreSaleWrapper.tsx, src/containers/PreSaleWrapper/styles.ts
update steps component, add shadow to current phase, change name of phases
show current phase on top
add valuation components
=> Small fixes

src/components/PreSale/BuyComponent/BuyComponent.tsx, src/components/PreSale/SaleStepper/style.ts, src/components/PreSale/Tokenomics/Tokenomics.tsx, src/containers/PreSaleWrapper/PreSaleWrapper.tsx, src/containers/PreSaleWrapper/styles.ts
Deleting phrase "public" from sale
=> Text changes and UI Fixes

src/components/PreSale/BuyComponent/BuyComponent.tsx, src/components/PreSale/BuyComponent/style.ts, src/components/PreSale/RoundComponent/RoundComponent.tsx, src/components/PreSale/RoundComponent/style.ts, src/containers/PreSaleWrapper/styles.ts
- “price” -> “ratio” 
-  Maximal rasie -> “Upper limit”
- 
- width of page
=> Sale small fixes

src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/RangeSelector/RangeSelector.tsx
Reverts invariant-labs/webapp-eclipse#1240
=> Revert "Set default price range for ES-USDC pool"

package-lock.json, src/components/PreSale/DEXChart/DEXChart.tsx, src/components/PreSale/RoundComponent/RoundComponent.tsx, src/components/PreSale/Tokenomics/Tokenomics.tsx, src/containers/PreSaleWrapper/PreSaleWrapper.tsx, src/pages/RootPage.tsx
=> presale texts update

src/components/PreSale/RoundComponent/RoundComponent.tsx, src/containers/PreSaleWrapper/PreSaleWrapper.tsx
Valuation value chagne to 4.5M
=> Valuation value chagne

src/components/PreSale/BuyComponent/BuyComponent.tsx, src/containers/PreSaleWrapper/PreSaleWrapper.tsx
Reverts invariant-labs/webapp-eclipse#1343
=> Revert "Update prod"

src/store/sagas/positions.ts, src/utils/utils.ts
- Prevent error with compute units when claiming fee from locked position
- Snackbars shows correct amounts when claiming fee from locked position
=> [526, 529] Lock claim and snackbar lock claim fix
